export const LOADING = 'LOADING'
export const CATEGORY_FINISH = 'CATEGORY_FINISH'



export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FINISH = 'PRODUCT_FINISH'
export const PRODUCT_DETAIL_LOADING = 'PRODUCT_DETAIL_LOADING';
export const PRODUCT_DETAIL_FINISH = 'PRODUCT_DETAIL_FINISH'
