export const LOADING = 'LOADING'
export const CATEGORY_FINISH = 'CATEGORY_FINISH'



export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FINISH = 'PRODUCT_FINISH'
export const PRODUCT_DETAIL_LOADING = 'PRODUCT_DETAIL_LOADING';
export const PRODUCT_DETAIL_FINISH = 'PRODUCT_DETAIL_FINISH'


export const USER_LOADING = 'USER_LOADING'
export const USER_LOGIN = 'USER_LOGIN'


export const CART_OPEN = 'CART_OPEN'
export const CART_CLOSE = 'CART_CLOSE'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'